"""add_account_number_to_object_rso_link

Revision ID: 2c60826df4c3
Revises: 5d72a3fb9b9d
Create Date: 2026-01-09 02:11:50.288976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c60826df4c3'
down_revision: Union[str, None] = '5d72a3fb9b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_rso_links', sa.Column('account_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_rso_links', 'account_number')
    # ### end Alembic commands ###
