"""make_provider_object_id_nullable

Revision ID: 5d72a3fb9b9d
Revises: 389b92bc0a6f
Create Date: 2026-01-09 02:04:55.879069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""make_provider_object_id_nullable

Revision ID: 5d72a3fb9b9d
Revises: 389b92bc0a6f
Create Date: 2026-01-09 02:04:55.879069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d72a3fb9b9d'
down_revision: Union[str, None] = '389b92bc0a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('comm_providers', schema=None) as batch_op:
        batch_op.alter_column('object_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    with op.batch_alter_table('object_rso_links', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('uq_object_provider'), type_='unique')

    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('tax_rate_snapshot', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.alter_column('reminder_count',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('1'))

    with op.batch_alter_table('tenant_stays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('tg_id',
                   existing_type=sa.BIGINT(),
                   nullable=True)
                   
    with op.batch_alter_table('uk_rso_links', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('uq_uk_provider'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uk_rso_links', schema=None) as batch_op:
        batch_op.create_unique_constraint(op.f('uq_uk_provider'), ['uk_id', 'provider_id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('tg_id',
                   existing_type=sa.BIGINT(),
                   nullable=False)

    with op.batch_alter_table('tenant_stays', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.alter_column('reminder_count',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('1'))

    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.drop_column('tax_rate_snapshot')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('base_amount')

    with op.batch_alter_table('object_rso_links', schema=None) as batch_op:
        batch_op.create_unique_constraint(op.f('uq_object_provider'), ['object_id', 'provider_id'])

    with op.batch_alter_table('comm_providers', schema=None) as batch_op:
        batch_op.alter_column('object_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
