"""add_source_field_to_comm_providers

Revision ID: e7a246c1d10c
Revises: a99f41ae61d0
Create Date: 2026-01-12 20:10:52.698760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
"""add_source_field_to_comm_providers

Revision ID: e7a246c1d10c
Revises: a99f41ae61d0
Create Date: 2026-01-12 20:10:52.698760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e7a246c1d10c'
down_revision: Union[str, None] = 'a99f41ae61d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the source field - other changes are artifacts from merge
    op.add_column('comm_providers', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comm_providers', 'source')
    # ### end Alembic commands ###
